version: '3.3'

services:
  bot:
    build: .
    container_name: ${BOT_CONTAINER_NAME}
    env_file:
      - .env
    command: python bot_v03.py
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: psyinc_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
